version: 0.2

env:
  variables:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCOUNT_ID: "042469170563"
      VERSION: 1.1.9
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 042469170563.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build version $VERSION started on `date`
      - docker build -t tumsa:$VERSION .
      - docker tag tumsa:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tumsa:$VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tumsa:$VERSION
